# Generated by Django 3.2.3 on 2021-05-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('batch', models.CharField(max_length=3)),
                ('program', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=50)),
                ('githubLink', models.URLField(max_length=100, null=True, unique=True)),
                ('linkedinLink', models.URLField(null=True, unique=True)),
                ('mastercv', models.URLField(max_length=300, unique=True)),
                ('resume1', models.URLField(max_length=300, unique=True)),
                ('resume2', models.URLField(max_length=300, null=True, unique=True)),
            ],
        ),
    ]
