# Generated by Django 3.2.3 on 2021-05-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume2',
            field=models.URLField(blank=True, default=False, max_length=300, unique=True),
        ),
    ]
