# Generated by Django 3.2.3 on 2021-05-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_resume2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume2',
            field=models.URLField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
