# Generated by Django 3.2.3 on 2021-06-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_resume2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='batch',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
