# Generated by Django 3.2.3 on 2021-05-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_text', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('eligible_batches', models.JSONField(default=dict)),
                ('eligible_branches', models.JSONField(default=dict)),
                ('eligible_programes', models.JSONField(default=dict)),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
            ],
        ),
    ]
