# Generated by Django 3.2.3 on 2021-06-04 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='placement_text',
        ),
        migrations.AddField(
            model_name='placement',
            name='placement_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placement',
            name='company',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='placement',
            name='description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='placement',
            name='eligible_batches',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='placement',
            name='eligible_branches',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='placement',
            name='eligible_programes',
            field=models.JSONField(default=list),
        ),
    ]
