# Generated by Django 3.2.3 on 2021-05-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intern_Name', models.CharField(max_length=500)),
                ('Company', models.CharField(max_length=500)),
                ('Duration', models.DurationField()),
                ('Role', models.CharField(max_length=5000)),
                ('Description', models.CharField(max_length=5000)),
                ('Eligible_Batches', models.JSONField(default=list)),
                ('Eligible_Branches', models.JSONField(default=list)),
                ('Eligible_Programs', models.JSONField(default=list)),
                ('Deadline', models.DateTimeField()),
                ('Intern_Start_Month', models.CharField(max_length=500)),
                ('Intern_End_Month', models.CharField(max_length=500)),
            ],
        ),
    ]
