# Generated by Django 3.2.4 on 2021-06-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '__first__'),
        ('intern', '__first__'),
        ('placement', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isIntern', models.ManyToManyField(blank=True, to='intern.Intern')),
                ('isPlacement', models.ManyToManyField(blank=True, to='placement.Placement')),
                ('user', models.ManyToManyField(blank=True, to='user.User')),
            ],
        ),
    ]
